'use strict';
const app=document.getElementById('app');
const num=Number(new URLSearchParams(location.search).get('niveau'));
const valid=Number.isInteger(num)&&num>=1&&num<=LEVELS.length;
let pos=0,answers=Array(20).fill(null),locked=Array(20).fill(false),ended=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const math=s=>esc(s).replace(/e\^\(([^()]*)\)/g,'e<sup>$1</sup>').replaceAll('abs(f(z))','|f(z)|').replaceAll('abs(1 + e^(it))','|1 + e^(it)|');
function best(i){try{return Number(localStorage.getItem('qfm-complexes-v1-'+i))||0;}catch{return 0;}}
function totals(){return {done:locked.filter(Boolean).length,score:valid?locked.reduce((s,v,i)=>s+(v&&answers[i]===LEVELS[num-1].questions[i].answer?1:0),0):0};}
function remember(score){try{localStorage.setItem('qfm-complexes-v1-'+num,String(Math.max(best(num),score)));}catch{}}
function home(){app.innerHTML=`<div class="eyebrow">Bac tunisien · Section Mathématiques</div><h1>Les complexes,<br>en dix étapes.</h1><p class="intro">Choisissez un niveau : 20 questions, quatre choix et une seule bonne réponse. Validez votre réponse pour lire la correction. Chaque quiz correspond à un exercice de la progression.</p><div class="grid">${LEVELS.map((l,i)=>`<a class="tile" href="?niveau=${i+1}"><span class="badge">${String(i+1).padStart(2,'0')}</span><div><h2>${esc(l.title)}</h2><div class="meta">20 questions · Correction expliquée${best(i+1)?` · Meilleur score : ${best(i+1)}/20`:''}</div></div></a>`).join('')}</div>`;}
function render(){if(!valid){home();return;}const level=LEVELS[num-1],q=level.questions[pos],t=totals();document.title=`QFM ${num} · ${level.title} · Faicel Missaoui`;app.innerHTML=`<div class="quiz"><a class="back" href="./">← Les dix niveaux</a><h1>${esc(level.title)}</h1><div class="top"><span>Niveau ${num} · ${t.done}/20 réponses validées</span><strong>Score : ${t.score}/20</strong></div><progress max="20" value="${t.done}" aria-label="Progression"></progress>${ended?`<section class="card"><div class="eyebrow">Bilan du niveau ${num}</div><h2>Quiz terminé</h2><div class="score">${t.score}<span> / 20</span></div><p>${t.score===20?'Toutes les réponses sont justes. Vérifiez maintenant que vous savez rédiger les solutions de l’exercice.':t.score>=16?'Les bases sont solides. Reprenez les corrections des questions manquées.':'Reprenez le rappel de cours et les corrections, puis refaites ce quiz.'}</p><div class="actions"><button class="primary" id="errors">${t.score===20?'Relire les corrections':'Revoir mes erreurs'}</button><button class="secondary" id="restart">Recommencer</button>${num<10?`<a class="primary" href="?niveau=${num+1}">Niveau suivant →</a>`:''}</div></section>`:`<section class="card"><div class="eyebrow">Question ${pos+1} sur 20</div><h2 id="question" tabindex="-1">${math(q.q)}</h2><div class="options" role="group" aria-labelledby="question">${q.options.map((o,i)=>`<button class="option ${answers[pos]===i?'selected':''} ${locked[pos]&&i===q.answer?'correct':''} ${locked[pos]&&answers[pos]===i&&i!==q.answer?'wrong':''}" data-choice="${i}" aria-pressed="${answers[pos]===i}" ${locked[pos]?'disabled':''}><span class="letter">${'ABCD'[i]}</span><span>${math(o)}${locked[pos]&&i===q.answer?' · ✓ Bonne réponse':''}${locked[pos]&&answers[pos]===i&&i!==q.answer?' · Votre réponse':''}</span></button>`).join('')}</div>${locked[pos]?`<div class="feedback" role="status"><strong>${answers[pos]===q.answer?'Réponse juste':'À reprendre'}</strong><p>${math(q.explanation)}</p></div>`:''}<div class="actions"><button class="secondary" id="prev" ${pos===0?'disabled':''}>← Précédente</button>${!locked[pos]?`<button class="primary" id="validate" ${answers[pos]===null?'disabled':''}>Valider</button>`:`<button class="primary" id="next">${t.done===20?'Voir le bilan':pos<19?'Suivante →':'Question restante →'}</button>`}</div></section>`}<nav class="nav" aria-label="Questions du quiz">${level.questions.map((x,i)=>`<button data-jump="${i}" class="${!ended&&i===pos?'current':''} ${locked[i]?(answers[i]===x.answer?'good':'bad'):''}" aria-label="Question ${i+1}${locked[i]?(answers[i]===x.answer?', réponse juste':', à reprendre'): ', non validée'}">${i+1}</button>`).join('')}</nav><p class="meta">Les réponses validées sont verrouillées. Un clic sur un numéro permet de relire la question et sa correction.</p></div>`;
app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{answers[pos]=Number(b.dataset.choice);render();document.getElementById('validate')?.focus();});
app.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{pos=Number(b.dataset.jump);ended=false;render();});
const bind=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn;};
bind('prev',()=>{if(pos>0)pos--;render();});bind('validate',()=>{if(answers[pos]===null||locked[pos])return;locked[pos]=true;if(totals().done===20)remember(totals().score);render();});bind('next',()=>{if(totals().done===20){ended=true;remember(totals().score);}else{pos=pos<19?pos+1:locked.findIndex(x=>!x);}render();document.getElementById('question')?.focus();});bind('errors',()=>{ended=false;pos=level.questions.findIndex((x,i)=>answers[i]!==x.answer);if(pos<0)pos=0;render();});bind('restart',()=>{answers=Array(20).fill(null);locked=Array(20).fill(false);pos=0;ended=false;render();});}
document.getElementById('share').onclick=async()=>{const url=location.href;const title=valid?`QFM ${num} · ${LEVELS[num-1].title}`:'QFM · 10 quiz sur les complexes';try{if(navigator.share){await navigator.share({title,text:title+' — 20 questions corrigées par niveau. Faicel Missaoui.',url});}else if(navigator.clipboard){await navigator.clipboard.writeText(url);document.getElementById('message').textContent='Lien copié : collez-le dans WhatsApp.';}else{prompt('Copiez ce lien pour le partager :',url);}}catch(e){if(e.name!=='AbortError')document.getElementById('message').textContent='Copiez l’adresse de cette page pour la partager.';}};
render();
