let order=questions.map((_,i)=>i),pos=0,picks={},validated={},finished=false,review=false;
const $=id=>document.getElementById(id);
function totals(){const ids=Object.keys(validated);return {done:ids.length,score:ids.reduce((s,k)=>s+(picks[k]===questions[k].answer?1:0),0)};}
function current(){return order[pos];}
function render(){const t=totals();$('progress').value=t.done;$('progressLabel').textContent=`${t.done} / 30 réponses validées`;$('scoreLabel').textContent=`Score : ${t.score}`;$('chapters').innerHTML=chapters.map((c,j)=>`<div class="chapter ${!finished&&questions[current()].ch===j?'active':''}"><em>${j+1}</em><div>${c}</div><span>${questions.filter((q,i)=>q.ch===j&&validated[i]).length}/5</span></div>`).join('');
if(finished){$('questionArea').innerHTML=`<div class="card"><div class="eyebrow">BILAN DU QFM</div><h2>Votre parcours est terminé.</h2><div class="result-score">${t.score}<small> / 30</small></div><p>${t.score===30?'Toutes les réponses sont justes. Bravo pour ce parcours !':t.score>=24?'Les notions sont bien maîtrisées. Reprenez les quelques points à consolider.':'Reprenez les corrections, puis essayez à nouveau les questions qui vous ont posé difficulté.'}</p>${chapters.map((c,j)=>`<div class="result-row"><span>${c}</span><strong>${questions.filter((q,i)=>q.ch===j&&picks[i]===q.answer).length} / 5</strong></div>`).join('')}<div class="actions"><button id="restart" class="secondary">Recommencer</button>${t.score<30?'<button id="mistakes" class="primary">Revoir mes erreurs</button>':'<button id="reviewAll" class="primary">Revoir les corrections</button>'}</div><p class="privacy" style="display:block">Le score correspond aux réponses validées lors de cette session. Il n’est pas transmis.</p></div>`;$('restart').onclick=()=>{if(confirm('Recommencer le QFM et effacer les réponses de cette session ?')){picks={};validated={};order=questions.map((_,i)=>i);pos=0;finished=false;review=false;render();}};const m=$('mistakes')||$('reviewAll');m.onclick=()=>{order=questions.map((_,i)=>i).filter(i=>t.score===30||picks[i]!==questions[i].answer);pos=0;review=true;finished=false;render();};return;}
const id=current(),q=questions[id],v=validated[id],pick=picks[id],correct=pick===q.answer;
$('questionArea').innerHTML=`<article class="card" aria-labelledby="questionTitle"><div class="qtop"><span class="qnumber">${String(id+1).padStart(2,'0')}<span class="sr-only"> sur 30</span></span><span>TD ${q.ch<2?'1':'2'} · ${chapters[q.ch]}</span></div>${review?`<p class="review-label">Révision · ${pos+1} / ${order.length}</p>`:''}<div class="context">${q.ctx}</div><h2 id="questionTitle" tabindex="-1">${q.prompt}</h2><div class="options" role="group" aria-label="Choisir une réponse">${q.labels.map((a,i)=>`<button class="option ${pick===i?'selected':''} ${v&&i===q.answer?'correct':''} ${v&&pick===i&&!correct?'wrong':''}" data-choice="${i}" aria-pressed="${pick===i}" ${v?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span class="opt-text">${a}${v&&i===q.answer?'<span class="sr-only"> — Bonne réponse</span>':''}${v&&pick===i&&!correct?'<span class="sr-only"> — Votre réponse, incorrecte</span>':''}</span></button>`).join('')}</div><details><summary>Un indice</summary><p>${q.hint}</p></details>${v?`<div class="feedback ${correct?'good':'bad'}" role="status"><h3>${correct?'Bonne réponse.':'À reprendre.'}</h3>${!correct?`<p>${q.wrong[pick]}</p><p><strong>Réponse attendue : ${String.fromCharCode(65+q.answer)}.</strong></p>`:''}<p>${q.explanation}</p></div>`:''}<div class="actions"><button id="prev" class="secondary" ${pos===0?'disabled':''}>Précédente</button>${v?`<button id="next" class="primary">${pos===order.length-1?'Voir mon bilan':'Question suivante'}</button>`:`<button id="validate" class="primary" ${pick===undefined?'disabled':''}>Valider ma réponse</button>`}</div></article>`;
document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>select(Number(b.dataset.choice)));$('prev').onclick=()=>{if(pos>0){pos--;render();}};if($('validate'))$('validate').onclick=()=>validate();if($('next'))$('next').onclick=()=>advance();}
function select(i){if(!Number.isInteger(i)||i<0||i>3||finished||validated[current()])throw Error('Choix indisponible.');picks[current()]=i;render();}
function validate(){if(finished||picks[current()]===undefined||validated[current()])throw Error('Sélectionner une réponse non encore validée.');validated[current()]=true;render();}
function advance(){if(finished||!validated[current()])throw Error('Valider la réponse avant de continuer.');if(pos===order.length-1)finished=true;else pos++;render();$('questionArea').scrollIntoView({behavior:'auto',block:'start'});}
$('share').onclick=async()=>{const url=location.origin+location.pathname;try{if(navigator.share)await navigator.share({title:'QFM · Faicel Missaoui',text:'30 questions corrigées sur les deux TD de bac maths.',url});else{await navigator.clipboard.writeText(url);$('notice').textContent='Lien copié. Vous pouvez le coller dans WhatsApp.';}}catch(e){if(e.name!=='AbortError')$('notice').textContent='Pour partager, copiez l’adresse de cette page dans WhatsApp.';}};
render();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_qfm_question',description:'Lire la question courante et la progression sans modifier la session.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({finished,...totals(),question:finished?null:{id:questions[current()].id,prompt:questions[current()].prompt,context:questions[current()].ctx,options:questions[current()].labels,validated:!!validated[current()]}})});document.modelContext.registerTool({name:'submit_qfm_answer',description:'Choisir et valider une réponse à la question courante ; modifie le score de la session.',inputSchema:{type:'object',properties:{option:{type:'integer',minimum:0,maximum:3}},required:['option'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.option)||input.option<0||input.option>3)throw Error('Option attendue : entier de 0 à 3.');select(input.option);validate();return{correct:picks[current()]===questions[current()].answer,explanation:questions[current()].explanation,...totals()};}});}catch(e){/* Le QFM reste utilisable sans WebMCP. */}}
